config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  match "/auth/:provider" => "omniauth_callbacks#passthru", via: [:get, :post], as: :omniauth
  match "/auth/:provider/callback" => "omniauth_callbacks#callback", via: [:get, :post]
  get "sign_in" => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out

  resources :rides, except: [:show]
  resources :taxis, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ride.rb
class Ride < ApplicationRecord
  scope :sorted, -> { order(:date, :id) }

  belongs_to :user
  belongs_to :taxi

  validates :start_address, :destination_address, :price, :taxi, presence: true
  validates :price, numericality: true
  validates :date, date: true

  before_validation :fill_start_and_destination_coordinates
  after_validation :fill_distance

  def coordinates_blank?
    start_lat.blank? || start_lng.blank? || destination_lat.blank? || destination_lng.blank?
  end

  def coordinates_changed?
    start_lat_changed? || start_lng_changed? || destination_lat_changed? || destination_lng_changed?
  end

  private

  def fill_start_and_destination_coordinates
    fill_coordinates(:start) if start_address.present?
    fill_coordinates(:destination) if destination_address.present?
  end

  def fill_coordinates(prefix)
    return unless send("#{prefix}_address_changed?")

    results = Geocoder.search(send("#{prefix}_address"))
    if results[0]
      coordinates = results[0].coordinates
      send("#{prefix}_lat=", coordinates[0])
      send("#{prefix}_lng=", coordinates[1])
    else
      errors.add("#{prefix}_address", :not_found)
    end
  end

  def fill_distance
    return if coordinates_blank?
    return unless coordinates_changed?

    self.distance = Ride::CalculateDistance.call(
      start_lat:       start_lat,
      start_lng:       start_lng,
      destination_lat: destination_lat,
      destination_lng: destination_lng
    ).distance
  end
end

app/models/ride_stat.rb
class RideStat
  include ActiveModel::Model

  attr_reader :date
  attr_accessor :total_distance, :average_distance, :total_price, :average_price, :taxis

  def date=(value)
    @date = Date.parse(value)
  end
end

app/models/taxi.rb
class Taxi < ApplicationRecord
  scope :sorted, -> { order(:name) }
  scope :without_user, -> { where(user_id: nil) }
  scope :with_user_ids, ->(*user_ids) { where(user_id: user_ids) }

  belongs_to :user, required: false
  has_many :rides, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validate :check_name_with_global_taxi

  private

  def check_name_with_global_taxi
    errors.add(:name, :taken) if Taxi.without_user.where(name: name).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rides
  has_many :taxis

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to :sign_in, alert: t("unauthenticated") unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    monthly_statistic = Ride::MonthlyStatistic.call(user: current_user).collection
    weekly_statistic = Ride::WeeklyStatistic.call(user: current_user).statistic
    render locals: { monthly_statistic: monthly_statistic, weekly_statistic: weekly_statistic }
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  skip_before_action :authenticate_user!

  def callback
    interactor = User::FindOrCreateFromOmniauth.call(auth: request.env["omniauth.auth"])
    session[:user_id] = interactor.user.id
    redirect_to root_url
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def index
    rides = current_user.rides.sorted.includes(:taxi)
    render locals: { rides: rides }
  end

  def new
    ride = Ride.new(date: Time.zone.today)
    render locals: { ride: ride, taxis: global_with_user_taxis }
  end

  def create
    ride = Ride.new(ride_params.merge(user: current_user))
    if ride.save
      redirect_to :rides, notice: t("ride.created")
    else
      render :new, locals: { ride: ride, taxis: global_with_user_taxis }
    end
  end

  def edit
    ride = current_user.rides.find(params[:id])
    render locals: { ride: ride, taxis: global_with_user_taxis }
  end

  def update
    ride = current_user.rides.find(params[:id])
    if ride.update(ride_params)
      redirect_to :rides, notice: t("ride.updated")
    else
      render :new, locals: { ride: ride, taxis: global_with_user_taxis }
    end
  end

  def destroy
    ride = current_user.rides.find(params[:id])
    ride.destroy
    redirect_to :rides, notice: t("ride.deleted")
  end

  private

  def ride_params
    params.fetch(:ride, {}).permit(:start_address, :destination_address, :price, :taxi_id, :date)
  end

  def global_with_user_taxis
    Taxi.with_user_ids(nil, current_user.id).sorted
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/taxis_controller.rb
class TaxisController < ApplicationController
  def index
    global_taxis = Taxi.without_user.sorted
    taxis = current_user.taxis.sorted
    render locals: { global_taxis: global_taxis, taxis: taxis }
  end

  def new
    taxi = Taxi.new
    render locals: { taxi: taxi }
  end

  def create
    taxi = Taxi.new(taxi_params.merge(user: current_user))
    if taxi.save
      redirect_to :taxis, notice: t("taxi.created")
    else
      render :new, locals: { taxi: taxi }
    end
  end

  def edit
    taxi = current_user.taxis.find(params[:id])
    render locals: { taxi: taxi }
  end

  def update
    taxi = current_user.taxis.find(params[:id])
    if taxi.update(taxi_params)
      redirect_to :taxis, notice: t("taxi.updated")
    else
      render :new, locals: { taxi: taxi }
    end
  end

  def destroy
    taxi = current_user.taxis.find(params[:id])
    if taxi.rides.exists?
      redirect_to :taxis, notice: t("taxi.cannot_delete")
    else
      taxi.destroy
      redirect_to :taxis, notice: t("taxi.deleted")
    end
  end

  private

  def taxi_params
    params.fetch(:taxi, {}).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def distance_in_km(value)
    value.to_i / 1_000
  end
end

app/views/home/index.html.slim
h1.page-header  Current Week Stats

table.table.table-striped.table-bordered
  thead
    tr
      th  Rides sum
      th  Total price
  tbody
    - if weekly_statistic.total_distance.to_i > 0
      tr
        td = "#{number_with_delimiter(distance_in_km(weekly_statistic.total_distance), delimiter: " ")} km"
        td = number_to_currency(weekly_statistic.total_price, format: "%n %u", unit: "EUR", delimiter: " ")

h1.page-header  Current Month Stats

table.table.table-striped.table-bordered
  thead
    tr
      th  Day
      th  Rides sum
      th  Avg. ride
      th  Avg. price
      th  Taxis
  tbody
    - monthly_statistic.each do |element|
      tr
        td
          = element.date.strftime("%b, #{element.date.day.ordinalize}")
        td = "#{number_with_delimiter(distance_in_km(element.total_distance), delimiter: " ")} km"
        td = "#{number_with_delimiter(distance_in_km(element.average_distance), delimiter: " ")} km"
        td = number_to_currency(element.average_price, format: "%n %u", unit: "EUR", delimiter: " ")
        td = element.taxis

app/views/layouts/application.html.slim
doctype html
html
  head
    title Riderank
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  body
    nav.navbar.navbar-inverse.navbar-static-top
      .container
        .navbar-header
          - if current_user
            button.navbar-toggle.collapsed aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
          = link_to root_path, class: "navbar-brand" do
            | Riderank
        - if current_user
          #navbar.collapse.navbar-collapse
            ul.nav.navbar-nav
              li
                = link_to "Rides", rides_path
              li
                = link_to "Taxis", taxis_path
            ul.nav.navbar-nav.navbar-right
              li
                = link_to "Sign out", sign_out_path
    .container
      = render "shared/flash"
      = yield

app/views/rides/_form.html.slim
= form_for ride do |f|
  .form-group
    = f.label :start_address
    = f.text_field :start_address, class: "form-control"
    - if ride.errors[:start_address].any?
      .has-error
        p.help-block= ride.errors[:start_address].first

  .form-group
    = f.label :destination_address
    = f.text_field :destination_address, class: "form-control"
    - if ride.errors[:destination_address].any?
      .has-error
        p.help-block= ride.errors[:destination_address].first

  .form-group
    = f.label :price
    = f.text_field :price, class: "form-control"
    - if ride.errors[:price].any?
      .has-error
        p.help-block= ride.errors[:price].first

  .form-group
    = f.label :taxi_id
    = f.select :taxi_id, taxis.map { |taxi| [taxi.name, taxi.id] }, { include_blank: true }, class: "form-control"
    - if ride.errors[:taxi].any?
      .has-error
        p.help-block= ride.errors[:taxi].first

  .form-group
    = f.label :date
    = f.text_field :date, class: "form-control"
    - if ride.errors[:date].any?
      .has-error
        p.help-block= ride.errors[:date].first

  .actions
    = f.submit class: "btn btn-primary"
    | &nbsp;
    = link_to "Back", rides_path, class: "btn btn-default"

app/views/rides/edit.html.slim
h1.page-header Editing ride

== render "form", ride: ride, taxis: taxis

app/views/rides/index.html.slim
h1.page-header
  |  Rides&nbsp;
  = link_to "New Ride", new_ride_path, class: "btn btn-primary btn-xs"

table.table.table-striped.table-bordered
  thead
    tr
      th  Day
      th  Start Address
      th  Destination Address
      th  Distance
      th  Price
      th  Taxi
      th
        .pull-right  Action
  tbody
    - rides.each do |ride|
      tr
        td = l ride.date, format: :long
        td = ride.start_address
        td = ride.destination_address
        td = "#{number_with_delimiter(distance_in_km(ride.distance), delimiter: " ")} km"
        td = number_to_currency(ride.price, format: "%n %u", unit: "EUR", delimiter: " ")
        td = ride.taxi.name
        td
          .pull-right
            = link_to "Edit", edit_ride_path(ride), class: "btn btn-default btn-xs"
            | &nbsp;
            = link_to "Destroy", ride, data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger btn-xs"

app/views/rides/new.html.slim
h1.page-header New ride

== render "form", ride: ride, taxis: taxis

app/views/shared/_flash.html.slim
- if flash.notice || flash.alert
  .row
    .col-xs-12
      - if flash.notice
        .alert.alert-info
          = flash.notice
      - if flash.alert
        .alert.alert-danger
          = flash.alert

app/views/taxis/_form.html.slim
= form_for taxi do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
    - if taxi.errors[:name].any?
      .has-error
        p.help-block= taxi.errors[:name].first

  .actions
    = f.submit class: "btn btn-primary"
    | &nbsp;
    = link_to "Back", taxis_path, class: "btn btn-default"

app/views/taxis/edit.html.slim
h1.page-header Editing taxi

== render "form", taxi: taxi

app/views/taxis/index.html.slim
h1.page-header  Global Taxis

table.table.table-striped.table-bordered
  thead
    tr
      th  Name
  tbody
    - global_taxis.each do |taxi|
      tr
        td = taxi.name

h1.page-header
  |  User Taxis&nbsp;
  = link_to "New Taxi", new_taxi_path, class: "btn btn-primary btn-xs"

table.table.table-striped.table-bordered
  thead
    tr
      th  Name
      th
        .pull-right  Action
  tbody
    - taxis.each do |taxi|
      tr
        td = taxi.name
        td
          .pull-right
            = link_to "Edit", edit_taxi_path(taxi), class: "btn btn-default btn-xs"
            - unless taxi.rides.exists?
              | &nbsp;
              = link_to "Destroy", taxi, data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger btn-xs"

app/views/taxis/new.html.slim
h1.page-header New taxi

== render "form", taxi: taxi